[supabase]
url = "https://boffqphbqqamrnviowwj.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvZmZxcGhicXFhbXJudmlvd3dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY2NjQ2NjAsImV4cCI6MjA4MjI0MDY2MH0.aVJdKhUxIZYccjdSshhCzKAkIQJFgw_r0gr1YF10D0A"
